### ISSUE TITLE
ADMIN permission issue?

### ISSUE THREAD

**Issue by poVoq** [db0/threativore#13]
I am currently testing version 0.4.1 of this, but when I message the bot from the `THREATIVORE_ADMIN_URL` specified user to add another moderator I only get `Problem encountered when parsing operation: Sorry, you do not have enough rights to do a users operation.` as the response.

I don't really see any issue with my setup and have triple checked for typos. Any idea what might be going wrong?

**Comment by db0** [comment]
What do you set your `THREATIVORE_ADMIN_URL` to? Can you show me your env file without a password?

**Comment by poVoq** [comment]
I am using a container built from the included Dockerfile with Podman.

The env variables I tried are

`THREATIVORE_ADMIN_URL='https://slrpnk.net/u/povoq'`
and `THREATIVORE_ADMIN_URL=https://slrpnk.net/u/povoq`

I don't think this is an issue with the env variable itself as the other settings via env variables work fine.

**Comment by db0** [comment]
It's OK, I needed to confirm. Can you do other operations like adding a filter?

**Comment by poVoq** [comment]
Yes that seems to work.

Edit: I have not yet added the bot as an admin to the Lemmy instance itself, if that matters.

**Comment by poVoq** [comment]
Confirmed working now.
